### ISSUE TITLE
Independent Player bounty system

### ISSUE THREAD

**Issue by SteamDosh** [SkyrimTogether/issues-game#11]
## Description

Able to set bountys on players to claim gold

## Your environment

* Game edition (choose on which edition do you have problems):
    * The Elder Scrolls V: Skyrim
    * The Elder Scrolls V: Skyrim Special Edition

## Expected result

Use gold to broadcast a bounty, person who kills said player claims gold.

## Milestones
- [ ] Check player has sufficient gold for request
- [ ] Register bounty with Server
- [ ] Broadcast Bounty
- [ ] Claim bounty on kill

**Comment by SteamDosh** [comment]
After review, this can be created in a mod with mod-api in future.
